<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="ActiproSoftware.Controls.Avalonia.Pro" />
    <ProjectReference Include="../DynamicUI24.Core/DynamicUI24.Core.csproj" />
    <ProjectReference Include="../DynamicUI24.Shared/DynamicUI24.Shared.csproj" />
  </ItemGroup>
</Project>
